<?php

namespace Egal\Tests\Model;

use Egal\Model\Metadata\ModelMetadata;
use Egal\Model\Model;
use Egal\Tests\DatabaseSchema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Event;
use Laravel\Lumen\Application;
use PHPUnit\Framework\TestCase;

class FireActionModelEventsTest extends TestCase
{
    use DatabaseSchema;

    protected function createSchema(): void
    {
        $this->schema()->create('products', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->timestamps();
        });

        $productsAttributes = [
            ['id' => 1, 'name' => 'first_product'],
            ['id' => 2, 'name' => 'second_product'],
            ['id' => 3, 'name' => 'product_third'],
            ['id' => 4, 'name' => 'product_fourth'],
        ];

        foreach ($productsAttributes as $attributes) {
            FireActionModelEventsTestProductStub::create($attributes);
        }
    }

    protected function dropSchema(): void
    {
        $this->schema()->drop('products');
    }

    public function testActionEventsDataProvider()
    {
        return [
            [
                'updated.action',
                fn() => FireActionModelEventsTestProductStub::actionUpdate(1, ['name' => 'updated_product'])
            ]
        ];
    }

    /**
     * @dataProvider testActionEventsDataProvider
     * @group current
     */
    public function testFireActionModelEvents($event, $function)
    {
        $app = new Application(dirname(__DIR__));
        $app->withFacades();

        Event::fake();

        dump(call_user_func($function));

        Event::assertDispatched($event);
    }
}

class FireActionModelEventsTestProductStub extends Model
{

    protected $table = 'products';
    protected $guarded = [];
    protected $fillable = [];

    public function getModelMetadata(): ModelMetadata
    {
        return new ModelMetadata(static::class);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::retrieved(function (self $stub) {
            dump('retrieved');
        });
        static::updating(function (self $stub) {
            $dump = dump('updating');
        });
        static::updatedWithAction(function (self $stub) {
            dump('here');
        });
    }

}
