<?php

namespace EgalFramework\APIContainer\Tests\Samples;

require_once __DIR__ . '/TestAbstractClass.php';
require_once __DIR__ . '/TestTrait.php';

/**
 * Test class title
 *
 * Test description
 * @package EgalFramework\APIContainer\Tests\Assets
 *
 * @method-roles protectedAbstract2 test
// * @method protectedAbstract2(string $str)
 * @method-roles actionDo
 * @method-roles
 */
class TestClass extends TestAbstractClass
{

    use TestTrait;

    /**
     * Method summary
     *
     * Method description
     * can be very long
     * @param string $name Attribute description
     * @param string $fake
     * @return string
     */
    public function actionDo($name = '')
    {

    }

    /**
     * Overridden method
     *
     * Overridden method description
     * @roles
     */
    public function actionAbstractOverride()
    {

    }

    /**
     * Method
     * @param string $str
     */
    protected function protectedAbstract2(string $str)
    {
        parent::protectedAbstract(); // TODO: Change the autogenerated stub
    }

    /**
     * This method is protected
     */
    protected function protectedMethod()
    {

    }

    /**
     * This method is private
     */
    private function privateMethod()
    {

    }

    public function __test()
    {

    }

    public function noDescriptionMethod()
    {

    }

}
