name: Tests

on:
  pull_request: { }

jobs:

  PHPUnit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer
        run: |
          docker run --rm \
            --user "$(id -u):$(id -g)" \
            --workdir "/app" \
            --volume "${PWD}:/app" \
            composer install \
              --dev \
              --ignore-platform-reqs \
              --no-interaction
      - name: Run a PHPUnit
        run: |
          bash bin/phpunit.sh

  PHPCS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Diff files Metadata
        id: diff-files-metadata
        run: |
          WORKDIR='/data'
          GIT_DIFF="$(git diff --name-only --diff-filter=dr ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -E '(.php)$')"
          echo $GIT_DIFF
          for i in $(echo "${GIT_DIFF[@]}" | tr " " "\n"); do
              FILES="${FILE} ${WORKDIR}/${i}"
          done
          echo $FILES
          echo "::set-output name=files::$FILES"
          echo "::set-output name=workdir::$WORKDIR"
      - name: Install Composer
        run: |
          docker run --rm \
            --user "$(id -u):$(id -g)" \
            --workdir "/app" \
            --volume "${PWD}:/app" \
            composer install \
              --dev \
              --ignore-platform-reqs \
              --no-interaction
      - name: Run a PHPCS
        run: |
          echo ${{ steps.diff-files-metadata.outputs.files }}
          bash bin/phpcs.sh ${{ steps.diff-files-metadata.outputs.files }}
