name: Tests

on:
  pull_request: { }

jobs:

  PHPUnit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer
        run: |
          docker run --rm \
            --user "$(id -u):$(id -g)" \
            --workdir "/app" \
            --volume "${PWD}:/app" \
            composer install \
              --dev \
              --ignore-platform-reqs \
              --no-interaction
      - name: Run a PHPUnit
        run: |
          bash bin/phpunit.sh

  PHPCS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install Composer
        run: |
          docker run --rm \
            --user "$(id -u):$(id -g)" \
            --workdir "/app" \
            --volume "${PWD}:/app" \
            composer install \
              --dev \
              --ignore-platform-reqs \
              --no-interaction
      - name: Run a PHPCS
        run: |
          DIFF="$(git diff \
            --name-only \
            --diff-filter=dr \
            ${{ github.event.pull_request.base.sha }} \
            ${{ github.sha }} | grep -E '(.php)$' || test $? = 1)"
          if [ "${DIFF}" == '' ]; then exit 0; fi
          bash bin/phpcs.sh --warning-severity=0 $DIFF
